spring.application.name=api-usuarios
server.port=8080 

# 1. CORRECCIÓN DEL HOST: Cambiamos 'db-usuarios' por el nombre del contenedor de Docker
# 2. CORRECCIÓN DE LA BD: Cambiamos 'db_usuarios' por el nombre real que creaste en Postgres
spring.datasource.url=jdbc:postgresql://db_innovatech_usuarios:5432/db_innovatech_usuarios

# 3. VERIFICACIÓN DE CREDENCIALES
# Asegúrate de que coincidan con el entorno de variables (POSTGRES_USER y POSTGRES_PASSWORD) de tu docker-compose
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect