spring.application.name=api-usuarios

server.port=8080 

spring.datasource.url=jdbc:postgresql://db-usuarios:5432/db_usuarios
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esta propiedad sirve para ver mejor los errores de conexin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect